### ISSUE TITLE
Version déjà compliée

### ISSUE THREAD

**Issue by IIPoliII** [LeRapha/BDOFarmingSimulator#1]
Hello,
Est-ce que une version déjà complié est disponible quelque part (y'en pas dans releases)
Merchi

**Comment by LeRapha** [comment]
Hello !
Alors non j'ai pas encore fait de release parce que le développement vient tout juste de démarrer et j'avance assez lentement faute de temps :/ mais c'est cool de voir que le projet peut intéresser certaines personnes :)

**Comment by IIPoliII** [comment]
Oui ça a l'air pas mal ton idée c:
